### ISSUE TITLE
Rebrand readme, program and code to not include GIF

### ISSUE THREAD

**Issue by thestar19** [thestar19/Animation-Generator-for-Sorting-Algorithms#27]
What:
The program and repo name contain the word GIF, but as the program supports more output formats than GIF, this should really change. Similarly, in multiple places in the code the word GIF is used, and this should probably be replaced with something like "Animation output".

How:
Change program name in display.py, do CTRL F and replace any mention of GIF in main, benchmark and display that is not specifically for creating GIF files. If parts of a section is also used for creating other formats, eg MP4, it should be renamed to instead reference animation.

**Comment by yr1404** [comment]
Do you want the program name to be "Sorting Algorithm **Animation output** Generator"??

**Comment by thestar19** [comment]
@yr1404 I don't know. The original name is "[Sorting-Algorithms-Visualizer](https://github.com/LucasPilla/Sorting-Algorithms-Visualizer)" by LucasPilla. I changed it to GIF generator bc that was all that the program did. Obviously, this program currently generates more than GIF files so the code & name needs to change. Sorting Algorithm Animation Output Generator is a really long name, so IDK. I am open to suggestions.

**Comment by yr1404** [comment]
I could suggest some names
- Sorting Algorithms Canvas
- Sorting Algorithms Imagery  
  
Or simply
- Sorting Algorithms Animation Generator

**Comment by thestar19** [comment]
Honestly, most of these are better than having GIF in the repo name and in like half of the variables. So the name of the repo doesn't really matter, it is mostly having variable names that include GIF when it is not relevant that annoys me. ChatGPT suggests these:

    Sorting Algorithms Visualizer
    Animation Generator for Sorting Algorithms
    Sorting Algorithm Animation Creator
    Sorting Algorithm Visualization Tool
    Sorting Algorithm Animation Engine
    Sorting Algorithm Animation Producer
    Sorting Algorithm Animation Composer
    Sorting Algorithm Animated Demonstrator
    Sorting Algorithm Visualization Studio
    Sorting Algorithm Animation Builder

**Comment by thestar19** [comment]
This issue will be closed for now as the necessary change has been made. The name "Animation Generator for Sorting Algorithms" is not great, so if anyone has a better idea, please create an issue and suggest it.
